// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tiny_ecg_no_activ_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer4_out_dout,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer4_out_empty_n,
        layer4_out_read,
        layer5_out_din,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap,
        layer5_out_full_n,
        layer5_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [19:0] layer4_out_dout;
input  [1:0] layer4_out_num_data_valid;
input  [1:0] layer4_out_fifo_cap;
input   layer4_out_empty_n;
output   layer4_out_read;
output  [19:0] layer5_out_din;
input  [1:0] layer5_out_num_data_valid;
input  [1:0] layer5_out_fifo_cap;
input   layer5_out_full_n;
output   layer5_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer4_out_read;
reg layer5_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [9:0] void_compute_pool_buffer_1d_array_const_stream_array_0_kernel_data_5;
reg   [9:0] void_compute_pool_buffer_1d_array_const_stream_array_0_kernel_data_4;
reg   [31:0] sX_1;
reg   [31:0] pX_1;
reg    layer4_out_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln185_reg_317;
reg    layer5_out_blk_n;
reg   [0:0] and_ln145_reg_321;
wire   [0:0] icmp_ln185_fu_123_p2;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] and_ln145_fu_155_p2;
wire   [0:0] icmp_ln165_fu_167_p2;
reg    ap_enable_reg_pp0_iter0;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg   [31:0] ap_phi_mux_storemerge_phi_fu_84_p4;
wire   [31:0] add_ln172_fu_187_p2;
wire   [31:0] ap_phi_reg_pp0_iter0_storemerge_reg_81;
wire    ap_CS_fsm_state4;
wire   [31:0] add_ln165_fu_161_p2;
reg   [7:0] i_iw_fu_56;
wire   [7:0] i_iw_4_fu_129_p2;
reg   [9:0] p_0_0_0_0_047_fu_60;
wire   [9:0] trunc_ln187_fu_211_p1;
reg   [9:0] p_0_1_0_0_050_fu_64;
wire   [9:0] trunc_ln187_4_fu_215_p4;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln145_fu_139_p2;
wire   [0:0] icmp_ln145_2_fu_149_p2;
wire   [31:0] select_ln172_fu_179_p3;
wire   [0:0] icmp_ln65_fu_225_p2;
wire   [0:0] xor_ln65_fu_231_p2;
wire   [0:0] icmp_ln65_4_fu_245_p2;
wire   [0:0] xor_ln65_4_fu_251_p2;
wire   [9:0] select_ln65_4_fu_257_p3;
wire   [9:0] select_ln65_fu_237_p3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_140;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 void_compute_pool_buffer_1d_array_const_stream_array_0_kernel_data_5 = 10'd0;
#0 void_compute_pool_buffer_1d_array_const_stream_array_0_kernel_data_4 = 10'd0;
#0 sX_1 = 32'd0;
#0 pX_1 = 32'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_iw_fu_56 <= 8'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln185_fu_123_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_iw_fu_56 <= i_iw_4_fu_129_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_140)) begin
        if ((icmp_ln165_fu_167_p2 == 1'd1)) begin
            pX_1 <= 32'd0;
        end else if ((icmp_ln165_fu_167_p2 == 1'd0)) begin
            pX_1 <= add_ln165_fu_161_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0_0_047_fu_60 <= void_compute_pool_buffer_1d_array_const_stream_array_0_kernel_data_5;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_0_0_047_fu_60 <= trunc_ln187_fu_211_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_1_0_0_050_fu_64 <= void_compute_pool_buffer_1d_array_const_stream_array_0_kernel_data_4;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_1_0_0_050_fu_64 <= {{layer4_out_dout[19:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln185_fu_123_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln145_reg_321 <= and_ln145_fu_155_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln185_reg_317 <= icmp_ln185_fu_123_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln185_fu_123_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sX_1 <= ap_phi_mux_storemerge_phi_fu_84_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        void_compute_pool_buffer_1d_array_const_stream_array_0_kernel_data_4 <= p_0_1_0_0_050_fu_64;
        void_compute_pool_buffer_1d_array_const_stream_array_0_kernel_data_5 <= p_0_0_0_0_047_fu_60;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((icmp_ln185_fu_123_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln185_fu_123_p2 == 1'd0)) begin
        if ((icmp_ln165_fu_167_p2 == 1'd1)) begin
            ap_phi_mux_storemerge_phi_fu_84_p4 = 32'd0;
        end else if ((icmp_ln165_fu_167_p2 == 1'd0)) begin
            ap_phi_mux_storemerge_phi_fu_84_p4 = add_ln172_fu_187_p2;
        end else begin
            ap_phi_mux_storemerge_phi_fu_84_p4 = ap_phi_reg_pp0_iter0_storemerge_reg_81;
        end
    end else begin
        ap_phi_mux_storemerge_phi_fu_84_p4 = ap_phi_reg_pp0_iter0_storemerge_reg_81;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln185_reg_317 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer4_out_blk_n = layer4_out_empty_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln185_reg_317 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer4_out_read = 1'b1;
    end else begin
        layer4_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln145_reg_321) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer5_out_blk_n = layer5_out_full_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln145_reg_321) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer5_out_write = 1'b1;
    end else begin
        layer5_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln185_fu_123_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln185_fu_123_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln165_fu_161_p2 = (pX_1 + 32'd1);

assign add_ln172_fu_187_p2 = (sX_1 + select_ln172_fu_179_p3);

assign and_ln145_fu_155_p2 = (icmp_ln145_fu_139_p2 & icmp_ln145_2_fu_149_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'd1 == and_ln145_reg_321) & (layer5_out_full_n == 1'b0)) | ((icmp_ln185_reg_317 == 1'd0) & (layer4_out_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'd1 == and_ln145_reg_321) & (layer5_out_full_n == 1'b0)) | ((icmp_ln185_reg_317 == 1'd0) & (layer4_out_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'd1 == and_ln145_reg_321) & (layer5_out_full_n == 1'b0)) | ((icmp_ln185_reg_317 == 1'd0) & (layer4_out_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((1'd1 == and_ln145_reg_321) & (layer5_out_full_n == 1'b0)) | ((icmp_ln185_reg_317 == 1'd0) & (layer4_out_empty_n == 1'b0)));
end

always @ (*) begin
    ap_condition_140 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln185_fu_123_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_storemerge_reg_81 = 'bx;

assign ap_ready = internal_ap_ready;

assign i_iw_4_fu_129_p2 = (i_iw_fu_56 + 8'd1);

assign icmp_ln145_2_fu_149_p2 = (($signed(pX_1) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln145_fu_139_p2 = ((sX_1 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln165_fu_167_p2 = ((add_ln165_fu_161_p2 == 32'd183) ? 1'b1 : 1'b0);

assign icmp_ln185_fu_123_p2 = ((i_iw_fu_56 == 8'd183) ? 1'b1 : 1'b0);

assign icmp_ln65_4_fu_245_p2 = (($signed(p_0_1_0_0_050_fu_64) < $signed(trunc_ln187_4_fu_215_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_225_p2 = (($signed(p_0_0_0_0_047_fu_60) < $signed(trunc_ln187_fu_211_p1)) ? 1'b1 : 1'b0);

assign layer5_out_din = {{select_ln65_4_fu_257_p3}, {select_ln65_fu_237_p3}};

assign select_ln172_fu_179_p3 = ((icmp_ln145_fu_139_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd1);

assign select_ln65_4_fu_257_p3 = ((xor_ln65_4_fu_251_p2[0:0] == 1'b1) ? p_0_1_0_0_050_fu_64 : trunc_ln187_4_fu_215_p4);

assign select_ln65_fu_237_p3 = ((xor_ln65_fu_231_p2[0:0] == 1'b1) ? p_0_0_0_0_047_fu_60 : trunc_ln187_fu_211_p1);

assign start_out = real_start;

assign trunc_ln187_4_fu_215_p4 = {{layer4_out_dout[19:10]}};

assign trunc_ln187_fu_211_p1 = layer4_out_dout[9:0];

assign xor_ln65_4_fu_251_p2 = (icmp_ln65_4_fu_245_p2 ^ 1'd1);

assign xor_ln65_fu_231_p2 = (icmp_ln65_fu_225_p2 ^ 1'd1);

endmodule //tiny_ecg_no_activ_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_s
