// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer5_out_dout,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap,
        layer5_out_empty_n,
        layer5_out_read,
        layer6_out_din,
        layer6_out_num_data_valid,
        layer6_out_fifo_cap,
        layer6_out_full_n,
        layer6_out_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_pp0_stage0 = 6'd16;
parameter    ap_ST_fsm_state7 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [19:0] layer5_out_dout;
input  [1:0] layer5_out_num_data_valid;
input  [1:0] layer5_out_fifo_cap;
input   layer5_out_empty_n;
output   layer5_out_read;
output  [39:0] layer6_out_din;
input  [1:0] layer6_out_num_data_valid;
input  [1:0] layer6_out_fifo_cap;
input   layer6_out_full_n;
output   layer6_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer5_out_read;
reg layer6_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4;
reg   [31:0] sX_2;
reg   [31:0] pX_2;
wire   [5:0] outidx_1_address0;
reg    outidx_1_ce0;
wire   [1:0] outidx_1_q0;
wire   [5:0] w6_address0;
reg    w6_ce0;
wire  signed [6:0] w6_q0;
reg    layer5_out_blk_n;
wire    ap_CS_fsm_state4;
reg    layer6_out_blk_n;
wire    ap_CS_fsm_state7;
reg   [0:0] and_ln360_reg_693;
reg   [3:0] in_index18_reg_197;
reg   [5:0] ir17_reg_208;
reg   [9:0] acc16_reg_219;
reg   [9:0] acc_1214_reg_230;
reg   [9:0] acc_1312_reg_241;
reg   [9:0] acc_1410_reg_252;
wire   [9:0] trunc_ln28_fu_305_p1;
reg   [9:0] trunc_ln28_reg_667;
reg   [9:0] trunc_ln28_1_reg_672;
wire   [6:0] i_iw_fu_319_p2;
reg   [6:0] i_iw_reg_677;
wire   [0:0] icmp_ln360_fu_341_p2;
reg   [0:0] icmp_ln360_reg_685;
wire   [0:0] and_ln360_fu_367_p2;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_reg_697;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_reg_702;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_reg_707;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_20_reg_712;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_21_reg_717;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_22_reg_722;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_23_reg_727;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_24_reg_732;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [9:0] a_fu_411_p12;
reg  signed [9:0] a_reg_742;
wire   [3:0] in_index_fu_439_p3;
reg   [3:0] in_index_reg_752;
reg    ap_enable_reg_pp0_iter0;
wire   [5:0] ir_fu_447_p2;
reg   [5:0] ir_reg_757;
wire   [0:0] icmp_ln127_fu_453_p2;
reg   [0:0] icmp_ln127_reg_762;
wire   [9:0] acc_18_fu_572_p3;
reg   [9:0] acc_18_reg_766;
reg    ap_enable_reg_pp0_iter1;
wire   [9:0] acc_17_fu_580_p3;
reg   [9:0] acc_17_reg_772;
wire   [9:0] acc_16_fu_588_p3;
reg   [9:0] acc_16_reg_778;
wire   [9:0] acc_fu_596_p3;
reg   [9:0] acc_reg_784;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
wire    grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_start;
wire    grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_done;
wire    grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_idle;
wire    grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_ready;
wire   [9:0] grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9;
wire    grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9_ap_vld;
wire   [9:0] grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1;
wire    grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_ap_vld;
wire   [9:0] grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o;
wire    grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o_ap_vld;
wire   [9:0] grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o;
wire    grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o_ap_vld;
wire   [9:0] grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o;
wire    grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o_ap_vld;
wire   [9:0] grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o;
wire    grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o_ap_vld;
wire   [9:0] grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o;
wire    grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o_ap_vld;
wire   [9:0] grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o;
wire    grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o_ap_vld;
reg   [6:0] i_iw19_reg_185;
reg    ap_block_state1;
reg    ap_block_state7;
wire   [0:0] icmp_ln27_fu_655_p2;
reg   [3:0] ap_phi_mux_in_index18_phi_fu_201_p4;
wire    ap_block_pp0_stage0;
reg   [5:0] ap_phi_mux_ir17_phi_fu_212_p4;
wire   [31:0] select_ln391_fu_635_p3;
reg   [31:0] ap_phi_mux_storemerge_phi_fu_266_p4;
wire   [0:0] icmp_ln384_fu_618_p2;
reg    grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln127_fu_405_p1;
wire   [31:0] add_ln384_fu_613_p2;
wire   [29:0] tmp_fu_351_p4;
wire   [0:0] icmp_ln360_1_fu_361_p2;
wire   [3:0] in_index_2_fu_427_p2;
wire   [0:0] icmp_ln144_fu_433_p2;
wire   [14:0] mul_ln136_fu_466_p2;
wire  signed [9:0] tmp_8_fu_482_p6;
wire  signed [9:0] trunc_ln3_fu_472_p4;
wire  signed [10:0] sext_ln136_fu_496_p1;
wire  signed [10:0] sext_ln136_2_fu_500_p1;
wire   [10:0] sub_ln136_fu_504_p2;
wire   [0:0] icmp_ln136_5_fu_516_p2;
wire   [0:0] icmp_ln136_6_fu_522_p2;
wire   [0:0] or_ln136_6_fu_534_p2;
wire   [0:0] icmp_ln136_fu_510_p2;
wire   [0:0] or_ln136_fu_540_p2;
wire   [0:0] icmp_ln136_7_fu_528_p2;
wire   [0:0] or_ln136_7_fu_546_p2;
wire   [0:0] or_ln136_8_fu_566_p2;
wire   [9:0] acc_14_fu_552_p3;
wire   [9:0] acc_15_fu_560_p2;
wire   [31:0] add_ln391_fu_630_p2;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_231;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3 = 10'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2 = 10'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9 = 10'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1 = 10'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data = 10'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7 = 10'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5 = 10'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8 = 10'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6 = 10'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4 = 10'd0;
#0 sX_2 = 32'd0;
#0 pX_2 = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_start_reg = 1'b0;
end

tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_outidx_1_dEe #(
    .DataWidth( 2 ),
    .AddressRange( 40 ),
    .AddressWidth( 6 ))
outidx_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx_1_address0),
    .ce0(outidx_1_ce0),
    .q0(outidx_1_q0)
);

tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_1PeOg #(
    .DataWidth( 7 ),
    .AddressRange( 40 ),
    .AddressWidth( 6 ))
w6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w6_address0),
    .ce0(w6_ce0),
    .q0(w6_q0)
);

tiny_ecg_no_activ_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_start),
    .ap_done(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_done),
    .ap_idle(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_idle),
    .ap_ready(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_ready),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9_ap_vld(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9_ap_vld),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_ap_vld(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_ap_vld),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_i(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o_ap_vld(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o_ap_vld),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_i(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o_ap_vld(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o_ap_vld),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_i(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o_ap_vld(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o_ap_vld),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_i(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o_ap_vld(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o_ap_vld),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_i(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o_ap_vld(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o_ap_vld),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_i(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o_ap_vld(grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o_ap_vld)
);

tiny_ecg_no_activ_mux_10_4_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 10 ),
    .din4_WIDTH( 10 ),
    .din5_WIDTH( 10 ),
    .din6_WIDTH( 10 ),
    .din7_WIDTH( 10 ),
    .din8_WIDTH( 10 ),
    .din9_WIDTH( 10 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 10 ))
mux_10_4_10_1_1_U35(
    .din0(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_reg_697),
    .din1(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_reg_702),
    .din2(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_reg_707),
    .din3(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_20_reg_712),
    .din4(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_21_reg_717),
    .din5(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_22_reg_722),
    .din6(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_23_reg_727),
    .din7(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_24_reg_732),
    .din8(trunc_ln28_reg_667),
    .din9(trunc_ln28_1_reg_672),
    .din10(ap_phi_mux_in_index18_phi_fu_201_p4),
    .dout(a_fu_411_p12)
);

tiny_ecg_no_activ_mul_10s_7s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_10s_7s_15_1_1_U36(
    .din0(a_reg_742),
    .din1(w6_q0),
    .dout(mul_ln136_fu_466_p2)
);

tiny_ecg_no_activ_mux_4_2_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 10 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 10 ))
mux_4_2_10_1_1_U37(
    .din0(acc16_reg_219),
    .din1(acc_1214_reg_230),
    .din2(acc_1312_reg_241),
    .din3(acc_1410_reg_252),
    .din4(outidx_1_q0),
    .dout(tmp_8_fu_482_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'd1 == and_ln360_reg_693) & (layer6_out_full_n == 1'b0)) & (icmp_ln27_fu_655_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'd1 == and_ln360_fu_367_p2) & (layer5_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'd1 == and_ln360_fu_367_p2) & (layer5_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_start_reg <= 1'b1;
        end else if ((grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_ready == 1'b1)) begin
            grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln127_reg_762 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc16_reg_219 <= acc_fu_596_p3;
    end else if (((1'd1 == and_ln360_fu_367_p2) & (layer5_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc16_reg_219 <= 10'd8;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln127_reg_762 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_1214_reg_230 <= acc_16_fu_588_p3;
    end else if (((1'd1 == and_ln360_fu_367_p2) & (layer5_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_1214_reg_230 <= 10'd2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln127_reg_762 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_1312_reg_241 <= acc_17_fu_580_p3;
    end else if (((1'd1 == and_ln360_fu_367_p2) & (layer5_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_1312_reg_241 <= 10'd3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln127_reg_762 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_1410_reg_252 <= acc_18_fu_572_p3;
    end else if (((1'd1 == and_ln360_fu_367_p2) & (layer5_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_1410_reg_252 <= 10'd1019;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'd1 == and_ln360_reg_693) & (layer6_out_full_n == 1'b0)) & (icmp_ln27_fu_655_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        i_iw19_reg_185 <= i_iw_reg_677;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_iw19_reg_185 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln127_reg_762 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_index18_reg_197 <= in_index_reg_752;
    end else if (((1'd1 == and_ln360_fu_367_p2) & (layer5_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        in_index18_reg_197 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln127_reg_762 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ir17_reg_208 <= ir_reg_757;
    end else if (((1'd1 == and_ln360_fu_367_p2) & (layer5_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ir17_reg_208 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_231)) begin
        if ((icmp_ln384_fu_618_p2 == 1'd1)) begin
            pX_2 <= 32'd0;
        end else if ((icmp_ln384_fu_618_p2 == 1'd0)) begin
            pX_2 <= add_ln384_fu_613_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        a_reg_742 <= a_fu_411_p12;
        icmp_ln127_reg_762 <= icmp_ln127_fu_453_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_16_reg_778 <= acc_16_fu_588_p3;
        acc_17_reg_772 <= acc_17_fu_580_p3;
        acc_18_reg_766 <= acc_18_fu_572_p3;
        acc_reg_784 <= acc_fu_596_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((layer5_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        and_ln360_reg_693 <= and_ln360_fu_367_p2;
        i_iw_reg_677 <= i_iw_fu_319_p2;
        icmp_ln360_reg_685 <= icmp_ln360_fu_341_p2;
        trunc_ln28_1_reg_672 <= {{layer5_out_dout[19:10]}};
        trunc_ln28_reg_667 <= trunc_ln28_fu_305_p1;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2 <= {{layer5_out_dout[19:10]}};
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3 <= trunc_ln28_fu_305_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_index_reg_752 <= in_index_fu_439_p3;
        ir_reg_757 <= ir_fu_447_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'd1 == and_ln360_reg_693) & (layer6_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
        sX_2 <= ap_phi_mux_storemerge_phi_fu_266_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data <= grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1 <= grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln360_fu_367_p2) & (layer5_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_reg_697 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_reg_702 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_reg_707 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_20_reg_712 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_21_reg_717 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_22_reg_722 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_23_reg_727 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_24_reg_732 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4 <= grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5 <= grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6 <= grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7 <= grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8 <= grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9_ap_vld == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9 <= grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer5_out_empty_n == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln360_reg_693) & (layer6_out_full_n == 1'b0))) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln127_fu_453_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'd1 == and_ln360_reg_693) & (layer6_out_full_n == 1'b0)) & (icmp_ln27_fu_655_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln127_reg_762 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_in_index18_phi_fu_201_p4 = in_index_reg_752;
    end else begin
        ap_phi_mux_in_index18_phi_fu_201_p4 = in_index18_reg_197;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln127_reg_762 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_ir17_phi_fu_212_p4 = ir_reg_757;
    end else begin
        ap_phi_mux_ir17_phi_fu_212_p4 = ir17_reg_208;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        if ((icmp_ln384_fu_618_p2 == 1'd1)) begin
            ap_phi_mux_storemerge_phi_fu_266_p4 = 32'd0;
        end else if ((icmp_ln384_fu_618_p2 == 1'd0)) begin
            ap_phi_mux_storemerge_phi_fu_266_p4 = select_ln391_fu_635_p3;
        end else begin
            ap_phi_mux_storemerge_phi_fu_266_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_storemerge_phi_fu_266_p4 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'd1 == and_ln360_reg_693) & (layer6_out_full_n == 1'b0)) & (icmp_ln27_fu_655_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        layer5_out_blk_n = layer5_out_empty_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer5_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        layer5_out_read = 1'b1;
    end else begin
        layer5_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln360_reg_693) & (1'b1 == ap_CS_fsm_state7))) begin
        layer6_out_blk_n = layer6_out_full_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'd1 == and_ln360_reg_693) & (layer6_out_full_n == 1'b0)) & (1'd1 == and_ln360_reg_693) & (1'b1 == ap_CS_fsm_state7))) begin
        layer6_out_write = 1'b1;
    end else begin
        layer6_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outidx_1_ce0 = 1'b1;
    end else begin
        outidx_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w6_ce0 = 1'b1;
    end else begin
        w6_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'd1 == and_ln360_fu_367_p2) & (layer5_out_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((layer5_out_empty_n == 1'b1) & (1'd0 == and_ln360_fu_367_p2) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((1'd1 == and_ln360_reg_693) & (layer6_out_full_n == 1'b0)) & (icmp_ln27_fu_655_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((1'd1 == and_ln360_reg_693) & (layer6_out_full_n == 1'b0)) & (icmp_ln27_fu_655_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_14_fu_552_p3 = ((or_ln136_7_fu_546_p2[0:0] == 1'b1) ? acc_1410_reg_252 : 10'd0);

assign acc_15_fu_560_p2 = ($signed(trunc_ln3_fu_472_p4) + $signed(tmp_8_fu_482_p6));

assign acc_16_fu_588_p3 = ((icmp_ln136_5_fu_516_p2[0:0] == 1'b1) ? acc_15_fu_560_p2 : acc_1214_reg_230);

assign acc_17_fu_580_p3 = ((icmp_ln136_6_fu_522_p2[0:0] == 1'b1) ? acc_15_fu_560_p2 : acc_1312_reg_241);

assign acc_18_fu_572_p3 = ((or_ln136_8_fu_566_p2[0:0] == 1'b1) ? acc_14_fu_552_p3 : acc_15_fu_560_p2);

assign acc_fu_596_p3 = ((icmp_ln136_fu_510_p2[0:0] == 1'b1) ? acc_15_fu_560_p2 : acc16_reg_219);

assign add_ln384_fu_613_p2 = (pX_2 + 32'd1);

assign add_ln391_fu_630_p2 = (sX_2 + 32'd1);

assign and_ln360_fu_367_p2 = (icmp_ln360_fu_341_p2 & icmp_ln360_1_fu_361_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7 = ((1'd1 == and_ln360_reg_693) & (layer6_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_231 = (~((1'd1 == and_ln360_reg_693) & (layer6_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_start = grp_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth_fu_273_ap_start_reg;

assign i_iw_fu_319_p2 = (i_iw19_reg_185 + 7'd1);

assign icmp_ln127_fu_453_p2 = ((ap_phi_mux_ir17_phi_fu_212_p4 == 6'd39) ? 1'b1 : 1'b0);

assign icmp_ln136_5_fu_516_p2 = ((outidx_1_q0 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln136_6_fu_522_p2 = ((outidx_1_q0 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln136_7_fu_528_p2 = ((sext_ln136_2_fu_500_p1 != sub_ln136_fu_504_p2) ? 1'b1 : 1'b0);

assign icmp_ln136_fu_510_p2 = ((outidx_1_q0 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln144_fu_433_p2 = ((in_index_2_fu_427_p2 > 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_655_p2 = ((i_iw19_reg_185 == 7'd90) ? 1'b1 : 1'b0);

assign icmp_ln360_1_fu_361_p2 = (($signed(tmp_fu_351_p4) > $signed(30'd0)) ? 1'b1 : 1'b0);

assign icmp_ln360_fu_341_p2 = ((sX_2 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln384_fu_618_p2 = ((add_ln384_fu_613_p2 == 32'd91) ? 1'b1 : 1'b0);

assign in_index_2_fu_427_p2 = (ap_phi_mux_in_index18_phi_fu_201_p4 + 4'd1);

assign in_index_fu_439_p3 = ((icmp_ln144_fu_433_p2[0:0] == 1'b1) ? 4'd0 : in_index_2_fu_427_p2);

assign ir_fu_447_p2 = (ap_phi_mux_ir17_phi_fu_212_p4 + 6'd1);

assign layer6_out_din = {{{{acc_18_reg_766}, {acc_17_reg_772}}, {acc_16_reg_778}}, {acc_reg_784}};

assign or_ln136_6_fu_534_p2 = (icmp_ln136_6_fu_522_p2 | icmp_ln136_5_fu_516_p2);

assign or_ln136_7_fu_546_p2 = (or_ln136_fu_540_p2 | icmp_ln136_7_fu_528_p2);

assign or_ln136_8_fu_566_p2 = (or_ln136_6_fu_534_p2 | icmp_ln136_fu_510_p2);

assign or_ln136_fu_540_p2 = (or_ln136_6_fu_534_p2 | icmp_ln136_fu_510_p2);

assign outidx_1_address0 = zext_ln127_fu_405_p1;

assign select_ln391_fu_635_p3 = ((icmp_ln360_reg_685[0:0] == 1'b1) ? 32'd4 : add_ln391_fu_630_p2);

assign sext_ln136_2_fu_500_p1 = trunc_ln3_fu_472_p4;

assign sext_ln136_fu_496_p1 = tmp_8_fu_482_p6;

assign start_out = real_start;

assign sub_ln136_fu_504_p2 = ($signed(11'd0) - $signed(sext_ln136_fu_496_p1));

assign tmp_fu_351_p4 = {{pX_2[31:2]}};

assign trunc_ln28_fu_305_p1 = layer5_out_dout[9:0];

assign trunc_ln3_fu_472_p4 = {{mul_ln136_fu_466_p2[14:5]}};

assign w6_address0 = zext_ln127_fu_405_p1;

assign zext_ln127_fu_405_p1 = ap_phi_mux_ir17_phi_fu_212_p4;

endmodule //tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s
