// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tiny_ecg_no_activ_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_i,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_i,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_i,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_i,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_i,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_i,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15;
input  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16;
output  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9_ap_vld;
output  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_ap_vld;
input  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_i;
output  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o_ap_vld;
input  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_i;
output  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o_ap_vld;
input  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_i;
output  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o_ap_vld;
input  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_i;
output  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o_ap_vld;
input  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_i;
output  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o_ap_vld;
input  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_i;
output  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o_ap_vld;

reg ap_idle;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9_ap_vld;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_ap_vld;
reg[9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o_ap_vld;
reg[9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o_ap_vld;
reg[9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o_ap_vld;
reg[9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o_ap_vld;
reg[9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o_ap_vld;
reg[9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln166_fu_76_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] tmp_s_fu_104_p6;
wire   [1:0] trunc_ln169_fu_88_p1;
wire   [9:0] tmp_4_fu_130_p6;
reg   [2:0] i_iw_3_fu_52;
wire   [2:0] add_ln166_fu_82_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_iw;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

tiny_ecg_no_activ_mux_4_2_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 10 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 10 ))
mux_4_2_10_1_1_U23(
    .din0(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_i),
    .din1(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_i),
    .din2(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_i),
    .din3(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15),
    .din4(trunc_ln169_fu_88_p1),
    .dout(tmp_s_fu_104_p6)
);

tiny_ecg_no_activ_mux_4_2_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 10 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 10 ))
mux_4_2_10_1_1_U24(
    .din0(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_i),
    .din1(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_i),
    .din2(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_i),
    .din3(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16),
    .din4(trunc_ln169_fu_88_p1),
    .dout(tmp_4_fu_130_p6)
);

tiny_ecg_no_activ_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln166_fu_76_p2 == 1'd0)) begin
            i_iw_3_fu_52 <= add_ln166_fu_82_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_iw_3_fu_52 <= 3'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln166_fu_76_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_iw = 3'd0;
    end else begin
        ap_sig_allocacmp_i_iw = i_iw_3_fu_52;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_88_p1 == 2'd0) & (icmp_ln166_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_88_p1 == 2'd3) & (icmp_ln166_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o = tmp_4_fu_130_p6;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o = void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_i;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_88_p1 == 2'd3) & (icmp_ln166_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_88_p1 == 2'd3) & (icmp_ln166_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o = tmp_s_fu_104_p6;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o = void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_i;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_88_p1 == 2'd3) & (icmp_ln166_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_88_p1 == 2'd2) & (icmp_ln166_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o = tmp_4_fu_130_p6;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o = void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_i;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_88_p1 == 2'd2) & (icmp_ln166_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_88_p1 == 2'd2) & (icmp_ln166_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o = tmp_s_fu_104_p6;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o = void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_i;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_88_p1 == 2'd2) & (icmp_ln166_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_88_p1 == 2'd1) & (icmp_ln166_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o = tmp_4_fu_130_p6;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o = void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_i;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_88_p1 == 2'd1) & (icmp_ln166_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_88_p1 == 2'd0) & (icmp_ln166_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_88_p1 == 2'd1) & (icmp_ln166_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o = tmp_s_fu_104_p6;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o = void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_i;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_88_p1 == 2'd1) & (icmp_ln166_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln166_fu_82_p2 = (ap_sig_allocacmp_i_iw + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln166_fu_76_p2 = ((ap_sig_allocacmp_i_iw == 3'd4) ? 1'b1 : 1'b0);

assign trunc_ln169_fu_88_p1 = ap_sig_allocacmp_i_iw[1:0];

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1 = tmp_4_fu_130_p6;

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9 = tmp_s_fu_104_p6;

endmodule //tiny_ecg_no_activ_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth
