// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="tiny_ecg_no_activ_tiny_ecg_no_activ,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku115-flvb2104-2-e,HLS_INPUT_CLOCK=50.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.185500,HLS_SYN_LAT=4554,HLS_SYN_TPT=2993,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=5196,HLS_SYN_LUT=4997,HLS_VERSION=2023_1}" *)

module tiny_ecg_no_activ (
        input_layer_3_TDATA,
        layer11_out_TDATA,
        ap_clk,
        ap_rst_n,
        input_layer_3_TVALID,
        input_layer_3_TREADY,
        ap_start,
        layer11_out_TVALID,
        layer11_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [15:0] input_layer_3_TDATA;
output  [79:0] layer11_out_TDATA;
input   ap_clk;
input   ap_rst_n;
input   input_layer_3_TVALID;
output   input_layer_3_TREADY;
input   ap_start;
output   layer11_out_TVALID;
input   layer11_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_ap_start;
wire    conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_ap_done;
wire    conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_ap_continue;
wire    conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_ap_idle;
wire    conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_ap_ready;
wire    conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_start_out;
wire    conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_start_write;
wire    conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_input_layer_3_TREADY;
wire   [19:0] conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_layer2_out_din;
wire    conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_layer2_out_write;
wire    relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_ap_start;
wire    relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_ap_done;
wire    relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_ap_continue;
wire    relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_ap_idle;
wire    relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_ap_ready;
wire    relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_layer2_out_read;
wire   [19:0] relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_layer4_out_din;
wire    relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_layer4_out_write;
wire    relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_start_out;
wire    relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_start_write;
wire    pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_ap_start;
wire    pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_ap_done;
wire    pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_ap_continue;
wire    pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_ap_idle;
wire    pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_ap_ready;
wire    pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_start_out;
wire    pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_start_write;
wire    pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_layer4_out_read;
wire   [19:0] pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_layer5_out_din;
wire    pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_layer5_out_write;
wire    conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_ap_start;
wire    conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_ap_done;
wire    conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_ap_continue;
wire    conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_ap_idle;
wire    conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_ap_ready;
wire    conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_start_out;
wire    conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_start_write;
wire    conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_layer5_out_read;
wire   [39:0] conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_layer6_out_din;
wire    conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_layer6_out_write;
wire    relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_ap_start;
wire    relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_ap_done;
wire    relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_ap_continue;
wire    relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_ap_idle;
wire    relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_ap_ready;
wire    relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_layer6_out_read;
wire   [39:0] relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_layer8_out_din;
wire    relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_layer8_out_write;
wire    relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_start_out;
wire    relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_start_write;
wire    pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_ap_start;
wire    pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_ap_done;
wire    pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_ap_continue;
wire    pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_ap_idle;
wire    pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_ap_ready;
wire    pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_start_out;
wire    pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_start_write;
wire    pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_layer8_out_read;
wire   [39:0] pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_layer9_out_din;
wire    pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_layer9_out_write;
wire    dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_ap_start;
wire    dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_ap_done;
wire    dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_ap_continue;
wire    dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_ap_idle;
wire    dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_ap_ready;
wire    dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_layer9_out_read;
wire   [79:0] dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_layer11_out_TDATA;
wire    dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_layer11_out_TVALID;
wire    layer2_out_full_n;
wire   [19:0] layer2_out_dout;
wire   [1:0] layer2_out_num_data_valid;
wire   [1:0] layer2_out_fifo_cap;
wire    layer2_out_empty_n;
wire    layer4_out_full_n;
wire   [19:0] layer4_out_dout;
wire   [1:0] layer4_out_num_data_valid;
wire   [1:0] layer4_out_fifo_cap;
wire    layer4_out_empty_n;
wire    layer5_out_full_n;
wire   [19:0] layer5_out_dout;
wire   [1:0] layer5_out_num_data_valid;
wire   [1:0] layer5_out_fifo_cap;
wire    layer5_out_empty_n;
wire    layer6_out_full_n;
wire   [39:0] layer6_out_dout;
wire   [1:0] layer6_out_num_data_valid;
wire   [1:0] layer6_out_fifo_cap;
wire    layer6_out_empty_n;
wire    layer8_out_full_n;
wire   [39:0] layer8_out_dout;
wire   [1:0] layer8_out_num_data_valid;
wire   [1:0] layer8_out_fifo_cap;
wire    layer8_out_empty_n;
wire    layer9_out_full_n;
wire   [39:0] layer9_out_dout;
wire   [1:0] layer9_out_num_data_valid;
wire   [1:0] layer9_out_fifo_cap;
wire    layer9_out_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_din;
wire    start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_dout;
wire    start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_empty_n;
wire   [0:0] start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_din;
wire    start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_full_n;
wire   [0:0] start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_dout;
wire    start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_empty_n;
wire   [0:0] start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_din;
wire    start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_full_n;
wire   [0:0] start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_dout;
wire    start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_din;
wire    start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_dout;
wire    start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_empty_n;
wire   [0:0] start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_din;
wire    start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_full_n;
wire   [0:0] start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_dout;
wire    start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_din;
wire    start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_full_n;
wire   [0:0] start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_dout;
wire    start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_empty_n;

tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_full_n),
    .ap_done(conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_ap_done),
    .ap_continue(conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_ap_continue),
    .ap_idle(conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_ap_idle),
    .ap_ready(conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_ap_ready),
    .start_out(conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_start_out),
    .start_write(conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_start_write),
    .input_layer_3_TDATA(input_layer_3_TDATA),
    .input_layer_3_TVALID(input_layer_3_TVALID),
    .input_layer_3_TREADY(conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_input_layer_3_TREADY),
    .layer2_out_din(conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_layer2_out_din),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_full_n(layer2_out_full_n),
    .layer2_out_write(conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_layer2_out_write)
);

tiny_ecg_no_activ_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_s relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_ap_start),
    .start_full_n(start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_full_n),
    .ap_done(relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_ap_ready),
    .layer2_out_dout(layer2_out_dout),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_empty_n(layer2_out_empty_n),
    .layer2_out_read(relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_layer2_out_read),
    .layer4_out_din(relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_layer4_out_din),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_full_n(layer4_out_full_n),
    .layer4_out_write(relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_layer4_out_write),
    .start_out(relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_start_out),
    .start_write(relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_start_write)
);

tiny_ecg_no_activ_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_s pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_ap_start),
    .start_full_n(start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_full_n),
    .ap_done(pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_ap_done),
    .ap_continue(pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_ap_continue),
    .ap_idle(pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_ap_idle),
    .ap_ready(pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_ap_ready),
    .start_out(pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_start_out),
    .start_write(pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_start_write),
    .layer4_out_dout(layer4_out_dout),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_empty_n(layer4_out_empty_n),
    .layer4_out_read(pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_layer4_out_read),
    .layer5_out_din(pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_layer5_out_din),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_full_n(layer5_out_full_n),
    .layer5_out_write(pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_layer5_out_write)
);

tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_full_n),
    .ap_done(conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_ap_done),
    .ap_continue(conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_ap_continue),
    .ap_idle(conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_ap_idle),
    .ap_ready(conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_ap_ready),
    .start_out(conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_start_out),
    .start_write(conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_start_write),
    .layer5_out_dout(layer5_out_dout),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_empty_n(layer5_out_empty_n),
    .layer5_out_read(conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_layer5_out_read),
    .layer6_out_din(conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_layer6_out_din),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap),
    .layer6_out_full_n(layer6_out_full_n),
    .layer6_out_write(conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_layer6_out_write)
);

tiny_ecg_no_activ_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_s relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_ap_start),
    .start_full_n(start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_full_n),
    .ap_done(relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_ap_ready),
    .layer6_out_dout(layer6_out_dout),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap),
    .layer6_out_empty_n(layer6_out_empty_n),
    .layer6_out_read(relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_layer6_out_read),
    .layer8_out_din(relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_layer8_out_din),
    .layer8_out_num_data_valid(layer8_out_num_data_valid),
    .layer8_out_fifo_cap(layer8_out_fifo_cap),
    .layer8_out_full_n(layer8_out_full_n),
    .layer8_out_write(relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_layer8_out_write),
    .start_out(relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_start_out),
    .start_write(relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_start_write)
);

tiny_ecg_no_activ_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_s pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_full_n),
    .ap_done(pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_ap_done),
    .ap_continue(pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_ap_continue),
    .ap_idle(pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_ap_idle),
    .ap_ready(pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_ap_ready),
    .start_out(pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_start_out),
    .start_write(pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_start_write),
    .layer8_out_dout(layer8_out_dout),
    .layer8_out_num_data_valid(layer8_out_num_data_valid),
    .layer8_out_fifo_cap(layer8_out_fifo_cap),
    .layer8_out_empty_n(layer8_out_empty_n),
    .layer8_out_read(pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_layer8_out_read),
    .layer9_out_din(pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_layer9_out_din),
    .layer9_out_num_data_valid(layer9_out_num_data_valid),
    .layer9_out_fifo_cap(layer9_out_fifo_cap),
    .layer9_out_full_n(layer9_out_full_n),
    .layer9_out_write(pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_layer9_out_write)
);

tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_ap_start),
    .ap_done(dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_ap_ready),
    .layer9_out_dout(layer9_out_dout),
    .layer9_out_num_data_valid(layer9_out_num_data_valid),
    .layer9_out_fifo_cap(layer9_out_fifo_cap),
    .layer9_out_empty_n(layer9_out_empty_n),
    .layer9_out_read(dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_layer9_out_read),
    .layer11_out_TDATA(dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_layer11_out_TDATA),
    .layer11_out_TVALID(dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_layer11_out_TVALID),
    .layer11_out_TREADY(layer11_out_TREADY)
);

tiny_ecg_no_activ_fifo_w20_d1_S layer2_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_layer2_out_din),
    .if_full_n(layer2_out_full_n),
    .if_write(conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_layer2_out_write),
    .if_dout(layer2_out_dout),
    .if_num_data_valid(layer2_out_num_data_valid),
    .if_fifo_cap(layer2_out_fifo_cap),
    .if_empty_n(layer2_out_empty_n),
    .if_read(relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_layer2_out_read)
);

tiny_ecg_no_activ_fifo_w20_d1_S layer4_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_layer4_out_din),
    .if_full_n(layer4_out_full_n),
    .if_write(relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_layer4_out_write),
    .if_dout(layer4_out_dout),
    .if_num_data_valid(layer4_out_num_data_valid),
    .if_fifo_cap(layer4_out_fifo_cap),
    .if_empty_n(layer4_out_empty_n),
    .if_read(pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_layer4_out_read)
);

tiny_ecg_no_activ_fifo_w20_d1_S layer5_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_layer5_out_din),
    .if_full_n(layer5_out_full_n),
    .if_write(pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_layer5_out_write),
    .if_dout(layer5_out_dout),
    .if_num_data_valid(layer5_out_num_data_valid),
    .if_fifo_cap(layer5_out_fifo_cap),
    .if_empty_n(layer5_out_empty_n),
    .if_read(conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_layer5_out_read)
);

tiny_ecg_no_activ_fifo_w40_d1_S layer6_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_layer6_out_din),
    .if_full_n(layer6_out_full_n),
    .if_write(conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_layer6_out_write),
    .if_dout(layer6_out_dout),
    .if_num_data_valid(layer6_out_num_data_valid),
    .if_fifo_cap(layer6_out_fifo_cap),
    .if_empty_n(layer6_out_empty_n),
    .if_read(relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_layer6_out_read)
);

tiny_ecg_no_activ_fifo_w40_d1_S layer8_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_layer8_out_din),
    .if_full_n(layer8_out_full_n),
    .if_write(relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_layer8_out_write),
    .if_dout(layer8_out_dout),
    .if_num_data_valid(layer8_out_num_data_valid),
    .if_fifo_cap(layer8_out_fifo_cap),
    .if_empty_n(layer8_out_empty_n),
    .if_read(pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_layer8_out_read)
);

tiny_ecg_no_activ_fifo_w40_d1_S layer9_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_layer9_out_din),
    .if_full_n(layer9_out_full_n),
    .if_write(pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_layer9_out_write),
    .if_dout(layer9_out_dout),
    .if_num_data_valid(layer9_out_num_data_valid),
    .if_fifo_cap(layer9_out_fifo_cap),
    .if_empty_n(layer9_out_empty_n),
    .if_read(dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_layer9_out_read)
);

tiny_ecg_no_activ_start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0 start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_full_n),
    .if_write(conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_empty_n),
    .if_read(relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_ap_ready)
);

tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5hbi start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5hbi_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_din),
    .if_full_n(start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_full_n),
    .if_write(relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_start_write),
    .if_dout(start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_dout),
    .if_empty_n(start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_empty_n),
    .if_read(pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_ap_ready)
);

tiny_ecg_no_activ_start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0 start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_din),
    .if_full_n(start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_full_n),
    .if_write(pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_start_write),
    .if_dout(start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_dout),
    .if_empty_n(start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_empty_n),
    .if_read(conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_ap_ready)
);

tiny_ecg_no_activ_start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0 start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_full_n),
    .if_write(conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_empty_n),
    .if_read(relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_ap_ready)
);

tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9ibs start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9ibs_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_din),
    .if_full_n(start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_full_n),
    .if_write(relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_start_write),
    .if_dout(start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_dout),
    .if_empty_n(start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_empty_n),
    .if_read(pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_ap_ready)
);

tiny_ecg_no_activ_start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0 start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_din),
    .if_full_n(start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_full_n),
    .if_write(pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_start_write),
    .if_dout(start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_dout),
    .if_empty_n(start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_empty_n),
    .if_read(dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_ap_ready)
);

assign ap_done = dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_ap_done;

assign ap_idle = (relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_ap_idle & relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_ap_idle & pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_ap_idle & pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_ap_idle & dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_ap_idle & conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_ap_idle & conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_ap_idle);

assign ap_ready = conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_ap_continue = 1'b1;

assign conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_ap_start = ap_start;

assign conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_ap_continue = 1'b1;

assign conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_ap_start = start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_empty_n;

assign dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_ap_start = start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_empty_n;

assign input_layer_3_TREADY = conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_U0_input_layer_3_TREADY;

assign layer11_out_TDATA = dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_layer11_out_TDATA;

assign layer11_out_TVALID = dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_layer11_out_TVALID;

assign pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_ap_continue = 1'b1;

assign pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_ap_start = start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_empty_n;

assign pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_ap_continue = 1'b1;

assign pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_ap_start = start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_empty_n;

assign relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_ap_start = start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_empty_n;

assign relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_ap_start = start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_empty_n;

assign start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0_din = 1'b1;

assign start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0_din = 1'b1;

assign start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_U0_din = 1'b1;

assign start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0_din = 1'b1;

endmodule //tiny_ecg_no_activ
