// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        input_layer_3_TDATA,
        input_layer_3_TVALID,
        input_layer_3_TREADY,
        layer2_out_din,
        layer2_out_num_data_valid,
        layer2_out_fifo_cap,
        layer2_out_full_n,
        layer2_out_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_pp0_stage0 = 6'd16;
parameter    ap_ST_fsm_state7 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] input_layer_3_TDATA;
input   input_layer_3_TVALID;
output   input_layer_3_TREADY;
output  [19:0] layer2_out_din;
input  [1:0] layer2_out_num_data_valid;
input  [1:0] layer2_out_fifo_cap;
input   layer2_out_full_n;
output   layer2_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer2_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11;
reg   [31:0] sX_3;
reg   [31:0] pX_3;
wire   [3:0] outidx_2_address0;
reg    outidx_2_ce0;
wire   [0:0] outidx_2_q0;
wire   [3:0] w2_address0;
reg    w2_ce0;
wire  signed [7:0] w2_q0;
reg    input_layer_3_TDATA_blk_n;
wire    ap_CS_fsm_state4;
reg    layer2_out_blk_n;
wire    ap_CS_fsm_state7;
reg   [0:0] and_ln360_reg_557;
reg   [3:0] ir13_reg_177;
reg   [2:0] in_index14_reg_188;
reg   [9:0] acc12_reg_199;
reg   [9:0] acc_2110_reg_210;
wire   [9:0] trunc_ln28_fu_249_p1;
reg   [9:0] trunc_ln28_reg_536;
wire   [7:0] i_iw_fu_253_p2;
reg   [7:0] i_iw_reg_541;
wire   [0:0] icmp_ln360_fu_269_p2;
reg   [0:0] icmp_ln360_reg_549;
wire   [0:0] and_ln360_fu_295_p2;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_26_reg_561;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_27_reg_566;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_28_reg_571;
reg   [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_29_reg_576;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] ir_fu_323_p2;
reg   [3:0] ir_reg_591;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] icmp_ln127_fu_329_p2;
reg   [0:0] icmp_ln127_reg_596;
wire   [9:0] acc_23_fu_442_p3;
reg   [9:0] acc_23_reg_600;
reg    ap_enable_reg_pp0_iter1;
wire   [9:0] acc_fu_450_p3;
reg   [9:0] acc_reg_606;
wire   [2:0] in_index_fu_470_p3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
wire    grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_start;
wire    grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_done;
wire    grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_idle;
wire    grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_ready;
wire   [9:0] grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14;
wire    grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld;
wire   [9:0] grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o;
wire    grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld;
wire   [9:0] grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o;
wire    grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld;
wire   [9:0] grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o;
wire    grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld;
reg   [7:0] i_iw15_reg_165;
reg    ap_block_state1;
reg    ap_block_state7;
wire   [0:0] icmp_ln27_fu_527_p2;
reg   [3:0] ap_phi_mux_ir13_phi_fu_181_p4;
wire    ap_block_pp0_stage0;
wire   [31:0] select_ln391_fu_507_p3;
reg   [31:0] ap_phi_mux_storemerge_phi_fu_224_p4;
wire   [0:0] icmp_ln384_fu_490_p2;
reg    grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln127_fu_317_p1;
wire   [31:0] add_ln384_fu_485_p2;
wire   [29:0] tmp_fu_279_p4;
wire   [0:0] icmp_ln360_2_fu_289_p2;
wire  signed [9:0] a_fu_335_p7;
wire   [14:0] mul_ln136_fu_354_p2;
wire  signed [9:0] tmp_s_fu_370_p4;
wire  signed [9:0] trunc_ln5_fu_360_p4;
wire  signed [10:0] sext_ln136_fu_380_p1;
wire  signed [10:0] sext_ln136_3_fu_384_p1;
wire   [10:0] sub_ln136_fu_394_p2;
wire   [0:0] icmp_ln136_fu_400_p2;
wire   [0:0] xor_ln136_fu_388_p2;
wire   [0:0] or_ln136_fu_406_p2;
wire   [9:0] select_ln136_fu_412_p3;
wire   [9:0] acc_22_fu_436_p2;
wire   [9:0] acc_21_fu_420_p3;
wire   [9:0] acc_20_fu_428_p3;
wire   [2:0] in_index_3_fu_458_p2;
wire   [0:0] icmp_ln144_fu_464_p2;
wire   [31:0] add_ln391_fu_502_p2;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_input_layer_3_U_apdone_blk;
wire   [15:0] input_layer_3_TDATA_int_regslice;
wire    input_layer_3_TVALID_int_regslice;
reg    input_layer_3_TREADY_int_regslice;
wire    regslice_both_input_layer_3_U_ack_in;
reg    ap_condition_191;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10 = 10'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14 = 10'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13 = 10'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12 = 10'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11 = 10'd0;
#0 sX_3 = 32'd0;
#0 pX_3 = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_start_reg = 1'b0;
end

tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_outidx_2_bkb #(
    .DataWidth( 1 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
outidx_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx_2_address0),
    .ce0(outidx_2_ce0),
    .q0(outidx_2_q0)
);

tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_1Pcud #(
    .DataWidth( 8 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
w2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_address0),
    .ce0(w2_ce0),
    .q0(w2_q0)
);

tiny_ecg_no_activ_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_start),
    .ap_done(grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_done),
    .ap_idle(grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_idle),
    .ap_ready(grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_ready),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_31(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14(grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld(grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_i(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o(grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld(grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_i(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o(grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld(grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_i(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o(grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld(grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld)
);

tiny_ecg_no_activ_mux_5_3_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 10 ),
    .din4_WIDTH( 10 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 10 ))
mux_5_3_10_1_1_U8(
    .din0(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_26_reg_561),
    .din1(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_27_reg_566),
    .din2(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_28_reg_571),
    .din3(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_29_reg_576),
    .din4(trunc_ln28_reg_536),
    .din5(in_index14_reg_188),
    .dout(a_fu_335_p7)
);

tiny_ecg_no_activ_mul_10s_8s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_10s_8s_15_1_1_U9(
    .din0(a_fu_335_p7),
    .din1(w2_q0),
    .dout(mul_ln136_fu_354_p2)
);

tiny_ecg_no_activ_mux_2_1_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 10 ))
mux_2_1_10_1_1_U10(
    .din0(acc12_reg_199),
    .din1(acc_2110_reg_210),
    .din2(outidx_2_q0),
    .dout(tmp_s_fu_370_p4)
);

tiny_ecg_no_activ_regslice_both #(
    .DataWidth( 16 ))
regslice_both_input_layer_3_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(input_layer_3_TDATA),
    .vld_in(input_layer_3_TVALID),
    .ack_in(regslice_both_input_layer_3_U_ack_in),
    .data_out(input_layer_3_TDATA_int_regslice),
    .vld_out(input_layer_3_TVALID_int_regslice),
    .ack_out(input_layer_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_layer_3_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'd1 == and_ln360_reg_557) & (layer2_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln27_fu_527_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'd1 == and_ln360_fu_295_p2) & (input_layer_3_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'd1 == and_ln360_fu_295_p2) & (input_layer_3_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_start_reg <= 1'b1;
        end else if ((grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_ready == 1'b1)) begin
            grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln127_reg_596 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc12_reg_199 <= acc_fu_450_p3;
    end else if (((1'd1 == and_ln360_fu_295_p2) & (input_layer_3_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc12_reg_199 <= 10'd12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln127_reg_596 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_2110_reg_210 <= acc_23_fu_442_p3;
    end else if (((1'd1 == and_ln360_fu_295_p2) & (input_layer_3_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_2110_reg_210 <= 10'd1020;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'd1 == and_ln360_reg_557) & (layer2_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln27_fu_527_p2 == 1'd0))) begin
        i_iw15_reg_165 <= i_iw_reg_541;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_iw15_reg_165 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln127_reg_596 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_index14_reg_188 <= in_index_fu_470_p3;
    end else if (((1'd1 == and_ln360_fu_295_p2) & (input_layer_3_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        in_index14_reg_188 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln127_reg_596 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ir13_reg_177 <= ir_reg_591;
    end else if (((1'd1 == and_ln360_fu_295_p2) & (input_layer_3_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ir13_reg_177 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_191)) begin
        if ((icmp_ln384_fu_490_p2 == 1'd1)) begin
            pX_3 <= 32'd0;
        end else if ((icmp_ln384_fu_490_p2 == 1'd0)) begin
            pX_3 <= add_ln384_fu_485_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_23_reg_600 <= acc_23_fu_442_p3;
        acc_reg_606 <= acc_fu_450_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((input_layer_3_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        and_ln360_reg_557 <= and_ln360_fu_295_p2;
        i_iw_reg_541 <= i_iw_fu_253_p2;
        icmp_ln360_reg_549 <= icmp_ln360_fu_269_p2;
        trunc_ln28_reg_536 <= trunc_ln28_fu_249_p1;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10 <= trunc_ln28_fu_249_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln127_reg_596 <= icmp_ln127_fu_329_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ir_reg_591 <= ir_fu_323_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'd1 == and_ln360_reg_557) & (layer2_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
        sX_3 <= ap_phi_mux_storemerge_phi_fu_224_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11 <= grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12 <= grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13 <= grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14 <= grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln360_fu_295_p2) & (input_layer_3_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_26_reg_561 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_27_reg_566 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_28_reg_571 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_29_reg_576 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((input_layer_3_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln360_reg_557) & (layer2_out_full_n == 1'b0))) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln127_fu_329_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'd1 == and_ln360_reg_557) & (layer2_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln27_fu_527_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln127_reg_596 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_ir13_phi_fu_181_p4 = ir_reg_591;
    end else begin
        ap_phi_mux_ir13_phi_fu_181_p4 = ir13_reg_177;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        if ((icmp_ln384_fu_490_p2 == 1'd1)) begin
            ap_phi_mux_storemerge_phi_fu_224_p4 = 32'd0;
        end else if ((icmp_ln384_fu_490_p2 == 1'd0)) begin
            ap_phi_mux_storemerge_phi_fu_224_p4 = select_ln391_fu_507_p3;
        end else begin
            ap_phi_mux_storemerge_phi_fu_224_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_storemerge_phi_fu_224_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_layer_3_TDATA_blk_n = input_layer_3_TVALID_int_regslice;
    end else begin
        input_layer_3_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((input_layer_3_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        input_layer_3_TREADY_int_regslice = 1'b1;
    end else begin
        input_layer_3_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'd1 == and_ln360_reg_557) & (layer2_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln27_fu_527_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln360_reg_557) & (1'b1 == ap_CS_fsm_state7))) begin
        layer2_out_blk_n = layer2_out_full_n;
    end else begin
        layer2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'd1 == and_ln360_reg_557) & (layer2_out_full_n == 1'b0)) & (1'd1 == and_ln360_reg_557) & (1'b1 == ap_CS_fsm_state7))) begin
        layer2_out_write = 1'b1;
    end else begin
        layer2_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outidx_2_ce0 = 1'b1;
    end else begin
        outidx_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w2_ce0 = 1'b1;
    end else begin
        w2_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'd1 == and_ln360_fu_295_p2) & (input_layer_3_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((input_layer_3_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4) & (1'd0 == and_ln360_fu_295_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((1'd1 == and_ln360_reg_557) & (layer2_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln27_fu_527_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((1'd1 == and_ln360_reg_557) & (layer2_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln27_fu_527_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_20_fu_428_p3 = ((or_ln136_fu_406_p2[0:0] == 1'b1) ? select_ln136_fu_412_p3 : acc12_reg_199);

assign acc_21_fu_420_p3 = ((or_ln136_fu_406_p2[0:0] == 1'b1) ? acc_2110_reg_210 : 10'd0);

assign acc_22_fu_436_p2 = ($signed(trunc_ln5_fu_360_p4) + $signed(tmp_s_fu_370_p4));

assign acc_23_fu_442_p3 = ((outidx_2_q0[0:0] == 1'b1) ? acc_22_fu_436_p2 : acc_21_fu_420_p3);

assign acc_fu_450_p3 = ((outidx_2_q0[0:0] == 1'b1) ? acc_20_fu_428_p3 : acc_22_fu_436_p2);

assign add_ln384_fu_485_p2 = (pX_3 + 32'd1);

assign add_ln391_fu_502_p2 = (sX_3 + 32'd1);

assign and_ln360_fu_295_p2 = (icmp_ln360_fu_269_p2 & icmp_ln360_2_fu_289_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7 = ((1'd1 == and_ln360_reg_557) & (layer2_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_191 = (~((1'd1 == and_ln360_reg_557) & (layer2_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_start = grp_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth_fu_231_ap_start_reg;

assign i_iw_fu_253_p2 = (i_iw15_reg_165 + 8'd1);

assign icmp_ln127_fu_329_p2 = ((ap_phi_mux_ir13_phi_fu_181_p4 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln136_fu_400_p2 = ((sext_ln136_3_fu_384_p1 != sub_ln136_fu_394_p2) ? 1'b1 : 1'b0);

assign icmp_ln144_fu_464_p2 = ((in_index_3_fu_458_p2 > 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_527_p2 = ((i_iw15_reg_165 == 8'd186) ? 1'b1 : 1'b0);

assign icmp_ln360_2_fu_289_p2 = (($signed(tmp_fu_279_p4) > $signed(30'd0)) ? 1'b1 : 1'b0);

assign icmp_ln360_fu_269_p2 = ((sX_3 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln384_fu_490_p2 = ((add_ln384_fu_485_p2 == 32'd187) ? 1'b1 : 1'b0);

assign in_index_3_fu_458_p2 = (in_index14_reg_188 + 3'd1);

assign in_index_fu_470_p3 = ((icmp_ln144_fu_464_p2[0:0] == 1'b1) ? 3'd0 : in_index_3_fu_458_p2);

assign input_layer_3_TREADY = regslice_both_input_layer_3_U_ack_in;

assign ir_fu_323_p2 = (ap_phi_mux_ir13_phi_fu_181_p4 + 4'd1);

assign layer2_out_din = {{acc_23_reg_600}, {acc_reg_606}};

assign or_ln136_fu_406_p2 = (xor_ln136_fu_388_p2 | icmp_ln136_fu_400_p2);

assign outidx_2_address0 = zext_ln127_fu_317_p1;

assign select_ln136_fu_412_p3 = ((icmp_ln136_fu_400_p2[0:0] == 1'b1) ? acc12_reg_199 : 10'd0);

assign select_ln391_fu_507_p3 = ((icmp_ln360_reg_549[0:0] == 1'b1) ? 32'd4 : add_ln391_fu_502_p2);

assign sext_ln136_3_fu_384_p1 = trunc_ln5_fu_360_p4;

assign sext_ln136_fu_380_p1 = tmp_s_fu_370_p4;

assign start_out = real_start;

assign sub_ln136_fu_394_p2 = ($signed(11'd0) - $signed(sext_ln136_fu_380_p1));

assign tmp_fu_279_p4 = {{pX_3[31:2]}};

assign trunc_ln28_fu_249_p1 = input_layer_3_TDATA_int_regslice[9:0];

assign trunc_ln5_fu_360_p4 = {{mul_ln136_fu_354_p2[14:5]}};

assign w2_address0 = zext_ln127_fu_317_p1;

assign xor_ln136_fu_388_p2 = (outidx_2_q0 ^ 1'd1);

assign zext_ln127_fu_317_p1 = ap_phi_mux_ir13_phi_fu_181_p4;

endmodule //tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s
