// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_outidx_1_dEe (
    address0, ce0, q0, 
    reset, clk);

parameter DataWidth = 2;
parameter AddressWidth = 6;
parameter AddressRange = 40;
 
input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

 
(* rom_style = "distributed" *)reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
     
    $readmemh("./tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_outidx_1_dEe.dat", rom0);
end

  
always @(posedge clk) 
begin 
    if (ce0) 
    begin
        q0 <= rom0[address0];
    end
end


endmodule

