// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tiny_ecg_no_activ_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_31,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_i,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_i,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_i,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_31;
output  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld;
input  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_i;
output  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld;
input  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_i;
output  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld;
input  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_i;
output  [9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld;

reg ap_idle;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld;
reg[9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld;
reg[9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld;
reg[9:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln166_fu_60_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] tmp_fu_88_p6;
wire   [1:0] trunc_ln169_fu_72_p1;
reg   [2:0] i_iw_fu_42;
wire   [2:0] indvars_iv_next_fu_66_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_iw_5;
wire   [1:0] tmp_fu_88_p5;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

tiny_ecg_no_activ_mux_4_2_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 10 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 10 ))
mux_4_2_10_1_1_U1(
    .din0(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_i),
    .din1(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_i),
    .din2(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_i),
    .din3(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_31),
    .din4(tmp_fu_88_p5),
    .dout(tmp_fu_88_p6)
);

tiny_ecg_no_activ_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln166_fu_60_p2 == 1'd0)) begin
            i_iw_fu_42 <= indvars_iv_next_fu_66_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_iw_fu_42 <= 3'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln166_fu_60_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_iw_5 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_iw_5 = i_iw_fu_42;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_72_p1 == 2'd3) & (icmp_ln166_fu_60_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o = tmp_fu_88_p6;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o = void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_i;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_72_p1 == 2'd3) & (icmp_ln166_fu_60_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_72_p1 == 2'd2) & (icmp_ln166_fu_60_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o = tmp_fu_88_p6;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o = void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_i;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_72_p1 == 2'd2) & (icmp_ln166_fu_60_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_72_p1 == 2'd1) & (icmp_ln166_fu_60_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o = tmp_fu_88_p6;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o = void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_i;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_72_p1 == 2'd1) & (icmp_ln166_fu_60_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln169_fu_72_p1 == 2'd0) & (icmp_ln166_fu_60_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln166_fu_60_p2 = ((ap_sig_allocacmp_i_iw_5 == 3'd4) ? 1'b1 : 1'b0);

assign indvars_iv_next_fu_66_p2 = (ap_sig_allocacmp_i_iw_5 + 3'd1);

assign tmp_fu_88_p5 = ap_sig_allocacmp_i_iw_5[1:0];

assign trunc_ln169_fu_72_p1 = ap_sig_allocacmp_i_iw_5[1:0];

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14 = tmp_fu_88_p6;

endmodule //tiny_ecg_no_activ_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth
